typography_spectrum: 1
color:
  brandStrength: 0.4744681
  lightness: 0
  saturation: 1
  rhythmicContrast: 1
  brandColors:
    - '#FFFFFF'
    - '#7D0001'
    - '#803F39'
    - '#718459'
    - '#BCC192'
layout_spectrum: 0.6489362
author:
  name: Hector M. Ortega
  email: ortegasculpture@yahoo.com
logo: null
name: Ortega Sculpture
collections:
  - index:
      navigable: true
      path: /
      number: 15
      paginate: true
    feed:
      format: rss
      path: /rss.xml
      number: 10
    permalink:
      path: '/:title/'
