layout_spectrum: 1
name: Ortega Sculpture
collections:
  - index:
      navigable: true
      path: /
      number: 15
      paginate: true
    feed:
      format: rss
      path: /rss.xml
      number: 10
    permalink:
      path: '/:title/'
color:
  brandStrength: 0.2319149
  lightness: 1
  saturation: 1
  rhythmicContrast: 1
  brandColors:
    - '#FCF5EB'
    - '#1B1A19'
    - '#F32A47'
    - '#953E6B'
    - '#3F668F'
typography_spectrum: 1
